
--BIBLIOTECA

-- @C:\SQL\2.sql;

--CREAR USUARIO
connect system/admin;

--SI EXISTE USUARIO, ELIMINARLO
DROP USER alfa CASCADE;

--CREAR USUARIO
CREATE USER alfa IDENTIFIED BY admin DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp QUOTA UNLIMITED ON users;

--CREAR ROL 
DROP ROLE DESARROLLO;
CREATE ROLE DESARROLLO;

--CONCEDER PERMISOS
GRANT CREATE SESSION,
CREATE TABLE,
CREATE SEQUENCE,
CREATE ANY INDEX,
CREATE VIEW, 
CREATE TRIGGER TO DESARROLLO;

--ASIGNAR PERMISOS A ROL
GRANT DESARROLLO TO alfa;

disc system;



--------------------------------------------------

--CONECTAR USUARIO

CONN alfa/admin;

ALTER SESSION SET NLS_DATE_FORMAT= 'DD/MM/YYYY';

CREATE TABLE AUTOR(
	ID_AUTOR NUMBER(4),
	NOMBRE VARCHAR2(15) NOT NULL,
	APELLIDO VARCHAR2(25) NOT NULL,
	NACIONALIDAD VARCHAR2(20), 
	CONSTRAINT ID_AUTOR_PK PRIMARY KEY(ID_AUTOR)
);

CREATE SEQUENCE SEQ_ID_AUTOR START WITH 1 INCREMENT BY 1;

INSERT INTO AUTOR(ID_AUTOR,NOMBRE,APELLIDO,NACIONALIDAD) 
VALUES (SEQ_ID_AUTOR.NEXTVAL,'Hyacinthie','Landes','Canadiense');

INSERT INTO AUTOR(ID_AUTOR,NOMBRE,APELLIDO,NACIONALIDAD) 
VALUES (SEQ_ID_AUTOR.NEXTVAL,'Merla','Mabey','Argentina');

INSERT INTO AUTOR(ID_AUTOR,NOMBRE,APELLIDO,NACIONALIDAD)
VALUES (SEQ_ID_AUTOR.NEXTVAL,'Perla','Gomez','Mexicana');

INSERT INTO AUTOR(ID_AUTOR,NOMBRE,APELLIDO,NACIONALIDAD)
VALUES (SEQ_ID_AUTOR.NEXTVAL,'Andrew','Tanenbaum','Americana');




CREATE TABLE TEMA(
	ID_TEMA NUMBER(4),
	DESCRIPCION VARCHAR2(50) NOT NULL,
	CONSTRAINT ID_TEMA_PK PRIMARY KEY(ID_TEMA)
);

CREATE SEQUENCE SEQ_ID_TEMA START WITH 1 INCREMENT BY 1;

INSERT INTO TEMA(ID_TEMA,DESCRIPCION) VALUES
(SEQ_ID_TEMA.NEXTVAL,'Ficcion');

INSERT INTO TEMA(ID_TEMA,DESCRIPCION) VALUES
(SEQ_ID_TEMA.NEXTVAL,'Informatica');

INSERT INTO TEMA(ID_TEMA,DESCRIPCION) VALUES
(SEQ_ID_TEMA.NEXTVAL,'Deporte');

INSERT INTO TEMA(ID_TEMA,DESCRIPCION) VALUES
(SEQ_ID_TEMA.NEXTVAL,'Psicologia');


CREATE TABLE OBRA(
	ID_OBRA NUMBER(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	ANHO NUMBER(4),
	ID_AUTOR NUMBER(4),
	ID_TEMA NUMBER(4),
	CONSTRAINT ID_OBRA_PK PRIMARY KEY(ID_OBRA),
	CONSTRAINT ID_AUTOR_FK FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR),
	CONSTRAINT ID_TEMA_FK FOREIGN KEY(ID_TEMA) REFERENCES TEMA(ID_TEMA)
);

CREATE SEQUENCE SEQ_ID_OBRA START WITH 1 INCREMENT BY 1;

INSERT INTO OBRA(ID_OBRA, NOMBRE, ANHO, ID_AUTOR, ID_TEMA)
VALUES(SEQ_ID_OBRA.NEXTVAL, 'Base de datos relacional',2005,4,2);

INSERT INTO OBRA(ID_OBRA, NOMBRE, ANHO, ID_AUTOR, ID_TEMA)
VALUES(SEQ_ID_OBRA.NEXTVAL, 'Informatica basica',2004,4,2);

INSERT INTO OBRA(ID_OBRA, NOMBRE, ANHO, ID_AUTOR, ID_TEMA)
VALUES(SEQ_ID_OBRA.NEXTVAL, 'War of the Ewings',2018,1,1);

INSERT INTO OBRA(ID_OBRA, NOMBRE, ANHO, ID_AUTOR, ID_TEMA)
VALUES(SEQ_ID_OBRA.NEXTVAL, 'Wings of Hope',2019,2,3);

INSERT INTO OBRA(ID_OBRA, NOMBRE, ANHO, ID_AUTOR, ID_TEMA)
VALUES(SEQ_ID_OBRA.NEXTVAL, 'Un amour de sorciere',2018,3,4);

CREATE TABLE LIBRO(
	ID_LIBRO NUMBER(4),
	TITULO VARCHAR2(25),
	ANHO_IMPRESION NUMBER(4),
	ISBN VARCHAR2(20),
	CONSTRAINT ID_LIBRO_PK PRIMARY KEY(ID_LIBRO)
);

CREATE SEQUENCE SEQ_ID_LIBRO START WITH 1 INCREMENT BY 1;

INSERT INTO LIBRO(ID_LIBRO, TITULO,ANHO_IMPRESION,ISBN)
VALUES(SEQ_ID_LIBRO.NEXTVAL, 'Cape Fear', 2014, '917229228-8');

INSERT INTO LIBRO(ID_LIBRO, TITULO, ANHO_IMPRESION, ISBN)
VALUES(SEQ_ID_LIBRO.NEXTVAL, 'When in Rome', 2018, '218993087-1');

INSERT INTO LIBRO(ID_LIBRO, TITULO, ANHO_IMPRESION, ISBN)
VALUES(SEQ_ID_LIBRO.NEXTVAL, 'BASE DE DATOS I', 2006, '640692027-9');

INSERT INTO LIBRO(ID_LIBRO, TITULO, ANHO_IMPRESION, ISBN)
VALUES(SEQ_ID_LIBRO.NEXTVAL, 'INFORMATICA II', 2004, '716582184-8');



CREATE TABLE ESTA_EN(
	ID_OBRA NUMBER(4),
	ID_LIBRO NUMBER(4),
	CONSTRAINT ID_LIBRO_OBRA_PK PRIMARY KEY(ID_OBRA,ID_LIBRO)
);

INSERT INTO ESTA_EN(ID_OBRA,ID_LIBRO)
VALUES (1,3);

INSERT INTO ESTA_EN(ID_OBRA,ID_LIBRO)
VALUES (2,4);

INSERT INTO ESTA_EN(ID_OBRA,ID_LIBRO)
VALUES (3,1);

INSERT INTO ESTA_EN(ID_OBRA,ID_LIBRO)
VALUES (4,2);


CREATE TABLE PERSONA(
	ID_PERSONA NUMBER(4),
	NOMBRE VARCHAR2(15),
	APELLIDO  VARCHAR2(25),
	TELEFONO VARCHAR2(15),
	CONSTRAINT ID_PERSONA_PK PRIMARY KEY(ID_PERSONA)
);

CREATE SEQUENCE SEQ_ID_PERSONA START WITH 1 INCREMENT BY 1;

INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO, TELEFONO) 
VALUES (SEQ_ID_PERSONA.NEXTVAL, 'Clio','Torvey','593-550-3226');

INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO, TELEFONO) 
VALUES (SEQ_ID_PERSONA.NEXTVAL,'Latashia', 'Ullyott','108-496-6565');

INSERT INTO PERSONA(ID_PERSONA, NOMBRE, APELLIDO, TELEFONO) 
VALUES (SEQ_ID_PERSONA.NEXTVAL,'Reba', 'Strathern','567-770-4381');



CREATE TABLE PRESTAMO(
	ID_PERSONA NUMBER(4),
	ID_LIBRO NUMBER(4),
	FECHA DATE,
	CONSTRAINT ID_PRESTAMO_PK PRIMARY KEY(ID_PERSONA,ID_LIBRO)
);

-- CREATE SEQUENCE SEQ_ID_PRESTAMO START WITH 1 INCREMENT BY 1;

INSERT INTO PRESTAMO(ID_PERSONA, ID_LIBRO, FECHA)
VALUES (1, 4, '12/01/2020');

INSERT INTO PRESTAMO(ID_PERSONA, ID_LIBRO, FECHA)
VALUES (3, 2, '01/07/2018');

INSERT INTO PRESTAMO(ID_PERSONA, ID_LIBRO, FECHA)
VALUES (2, 1, '01/07/2018');

INSERT INTO PRESTAMO(ID_PERSONA, ID_LIBRO, FECHA)
VALUES (2, 3, '01/08/2018');

/*
si los cambios no se reflejan en el navegador, usar commit;....
SENTENCIA SQL;
COMMIT;

*/

clear screen;

-- set serveroutput on format wrapped;
-- begin
--     DBMS_OUTPUT.put_line('Comentario...');
-- end;
-- /

-- select * from AUTOR;
-- select * from LIBRO;
-- select * from OBRA;
-- select * from TEMA;
-- select * from PERSONA;
-- select * from PRESTAMO;
-- select * from ESTA_EN;


/* Obtener la lista de PERSONAS que hayan prestado algún libro
en el mes de Julio/2018 */

SELECT persona.ID_PERSONA, persona.NOMBRE, persona.APELLIDO, persona.TELEFONO 
FROM PERSONA persona, PRESTAMO prestamo
WHERE persona.ID_PERSONA = prestamo.ID_PERSONA
AND prestamo.FECHA BETWEEN '01/07/2018' AND '31/07/2018'; 

/* si se cierra sesion y se vuelve a abrir, se
pierde el formato establecido para la fecha */






/*
Listar los AUTORES cuyas OBRAS pertenecen a los años 2018 y 2019
*/

SELECT autor.ID_AUTOR, autor.NOMBRE, autor.APELLIDO
FROM AUTOR autor, OBRA obra
WHERE autor.ID_AUTOR = obra.ID_AUTOR
AND obra.ANHO BETWEEN 2018 AND 2019;









/*	Obtener el NombreObra y Año de las OBRAS que pertenezcan al AUTOR
llamado Andrew Tanenbaum y cuyo numero de TEMA sea el 2. */

SELECT obra.ID_OBRA, obra.NOMBRE, obra.ANHO
FROM OBRA obra, AUTOR autor
WHERE obra.ID_AUTOR = autor.ID_AUTOR
AND autor.NOMBRE= 'Andrew' AND autor.APELLIDO='Tanenbaum'
AND obra.ID_TEMA = 2; 







/* 
Obtener la """"cantidad"""" de los LIBROS que se imprimieron entre 
los años 2014 y 2019
 */
 SELECT libro.ID_LIBRO, libro.TITULO, libro.ANHO_IMPRESION, libro.ISBN
 FROM LIBRO libro
 WHERE libro.ANHO_IMPRESION BETWEEN 2014 AND 2019;


--aca si es cantidad
 SELECT COUNT(libro.ANHO_IMPRESION)
 FROM LIBRO libro
 WHERE libro.ANHO_IMPRESION BETWEEN 2014 AND 2019;



 


 /*
Listar el nombre de la PERSONA, la fecha del PRESTAMO y 
el titulo del LIBRO que hayan prestado los LIBROS con los 
titulos BASE DE DATOS I O INFORMATICA II

 */
 SELECT persona.NOMBRE, persona.APELLIDO, prestamo.FECHA, libro.TITULO
 FROM PERSONA persona, PRESTAMO prestamo, LIBRO libro
 WHERE persona.ID_PERSONA = prestamo.ID_PERSONA
 AND prestamo.ID_LIBRO = libro.ID_LIBRO
 AND (libro.TITULO='BASE DE DATOS I' OR libro.TITULO='INFORMATICA II');






/*
Listar los registros con los sgtes campos: Num_libro y 
titulo de los LIBROS, nombre y nacionalidad de AUTOR cuyo 
año de OBRA fue en el 2018.
*/


/* tengo dos obras del 2018...
 -	War of the Ewings
 - 	Un amour de sorciere

 ...... PROBLEMA: NO ESTA ASOCIADO LA OBRA un amour... A UN LIBRO
 						POR LO QUE EL RESULTADO SOLO DARA war of the ewings
*/



CREATE OR REPLACE VIEW AUTORES_OBRA_2018
(ID_LIBRO, TITULO_LIBRO, AUTOR, NACIONALIDAD, OBRA, ANHO)
AS
SELECT libro.ID_LIBRO, libro.TITULO, autor.NOMBRE, autor.NACIONALIDAD, obra.NOMBRE, obra.ANHO
FROM LIBRO libro, AUTOR autor, OBRA obra, ESTA_EN esta_en
WHERE obra.ANHO = 2018
AND obra.ID_AUTOR = autor.ID_AUTOR 
AND esta_en.ID_LIBRO=libro.ID_LIBRO AND esta_en.ID_OBRA=obra.ID_OBRA; 

SELECT * FROM AUTORES_OBRA_2018; 
--ver vista

DISC alfa;